[package]
name = "sigma-file-manager"
description = "Sigma File Manager v2"
version = "2.0.0-alpha.1"
license = "GPL-3.0-or-later"
authors = ["Aleksey Hoffman"]
repository = "https://github.com/aleksey-hoffman/sigma-file-manager/tree/v2"
edition = "2021"
rust-version = "1.88.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sigma_file_manager_tauri_v2_own_frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.1", features = [ "protocol-asset", "tray-icon", "image-png"] }
tauri-plugin-log = "2"
tauri-plugin-store = "2"
tauri-plugin-opener = "2.5.0"
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
sysinfo = "0.37"
trash = "5.2.5"
base64 = "0.22"
png = "0.17"
file_icon_provider = "1.0.0"
image = { version = "0.25", default-features = false, features = ["png"] }
lru = "0.12"
once_cell = "1.19"
tantivy = "0.22"
walkdir = "2.5"
rayon = "1.10"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows = { version = "0.58", features = [
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_System_Environment",
    "Win32_Foundation",
    "Win32_System_Ole",
    "Win32_Storage_FileSystem",
    "Win32_Graphics_Gdi",
    "Win32_System_Registry",
    "Win32_UI_WindowsAndMessaging",
] }
windows-sys = { version = "0.59", features = [
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_Environment",
] }
