[package]
name = "sigma-file-manager"
description = "Sigma File Manager v2"
version = "2.0.0-alpha.1"
license = "GPL-3.0-or-later"
authors = ["Aleksey Hoffman"]
repository = "https://github.com/aleksey-hoffman/sigma-file-manager/tree/v2"
edition = "2021"
rust-version = "1.88.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sigma_file_manager_tauri_v2_own_frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.1", features = [ "protocol-asset", "tray-icon", "image-png"] }
tauri-plugin-log = "2"
tauri-plugin-store = "2"
tauri-plugin-opener = "2.5.0"
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
sysinfo = "0.37"
